set(_CATKIN_CURRENT_PACKAGE "IMU_Visualizer")
set(IMU_Visualizer_VERSION "0.0.0")
set(IMU_Visualizer_MAINTAINER "michael <michael@todo.todo>")
set(IMU_Visualizer_PACKAGE_FORMAT "2")
set(IMU_Visualizer_BUILD_DEPENDS "rospy" "sensor_msgs")
set(IMU_Visualizer_BUILD_EXPORT_DEPENDS )
set(IMU_Visualizer_BUILDTOOL_DEPENDS "catkin")
set(IMU_Visualizer_BUILDTOOL_EXPORT_DEPENDS )
set(IMU_Visualizer_EXEC_DEPENDS "rospy" "sensor_msgs")
set(IMU_Visualizer_RUN_DEPENDS "rospy" "sensor_msgs")
set(IMU_Visualizer_TEST_DEPENDS )
set(IMU_Visualizer_DOC_DEPENDS )
set(IMU_Visualizer_URL_WEBSITE "")
set(IMU_Visualizer_URL_BUGTRACKER "")
set(IMU_Visualizer_URL_REPOSITORY "")
set(IMU_Visualizer_DEPRECATED "")